"""Default menu created automatically for every new business.

Stock starts at 0 on purpose: the business counts its real stock and
updates it in the Products page before selling.
"""

DEFAULT_MENU: list[dict] = [
    {"name": "Espresso", "price": 0.8, "category": "Hot Drinks", "is_active": True},
    {"name": "Macchiato e vogël", "price": 0.9, "category": "Hot Drinks", "is_active": True},
    {"name": "Macchiato e madhe", "price": 1.2, "category": "Hot Drinks", "is_active": True},
    {"name": "Cappuccino", "price": 1.5, "category": "Hot Drinks", "is_active": True},
    {"name": "Latte", "price": 1.8, "category": "Hot Drinks", "is_active": True},
    {"name": "Ice Latte", "price": 2.0, "category": "Hot Drinks", "is_active": True},
    {"name": "Çaj mali", "price": 1.0, "category": "Hot Drinks", "is_active": True},
    {"name": "Çaj i zi", "price": 1.0, "category": "Hot Drinks", "is_active": True},
    {"name": "Çaj kamomili", "price": 1.0, "category": "Hot Drinks", "is_active": True},
    {"name": "Nescafe", "price": 1.5, "category": "Hot Drinks", "is_active": True},
    {"name": "Hot Chocolate", "price": 1.8, "category": "Hot Drinks", "is_active": True},
    {"name": "Coca Cola", "price": 1.5, "category": "Cold Drinks", "is_active": True},
    {"name": "Coca Cola Zero", "price": 1.5, "category": "Cold Drinks", "is_active": True},
    {"name": "Fanta", "price": 1.5, "category": "Cold Drinks", "is_active": True},
    {"name": "Sprite", "price": 1.5, "category": "Cold Drinks", "is_active": True},
    {"name": "Schweppes", "price": 1.5, "category": "Cold Drinks", "is_active": True},
    {"name": "Ice Tea Peach", "price": 1.5, "category": "Cold Drinks", "is_active": True},
    {"name": "Ice Tea Lemon", "price": 1.5, "category": "Cold Drinks", "is_active": True},
    {"name": "Orange Juice", "price": 2.0, "category": "Cold Drinks", "is_active": True},
    {"name": "Apple Juice", "price": 2.0, "category": "Cold Drinks", "is_active": True},
    {"name": "Ujë 0.25L", "price": 0.8, "category": "Cold Drinks", "is_active": True},
    {"name": "Ujë 0.75L", "price": 1.5, "category": "Cold Drinks", "is_active": True},
    {"name": "Red Bull", "price": 2.5, "category": "Cold Drinks", "is_active": True},
    {"name": "Birrë Peja", "price": 2.0, "category": "Alcohol", "is_active": True},
    {"name": "Birrë Prishtina", "price": 2.0, "category": "Alcohol", "is_active": True},
    {"name": "Heineken", "price": 2.5, "category": "Alcohol", "is_active": True},
    {"name": "Corona", "price": 3.0, "category": "Alcohol", "is_active": True},
    {"name": "Verë e kuqe", "price": 3.0, "category": "Alcohol", "is_active": True},
    {"name": "Verë e bardhë", "price": 3.0, "category": "Alcohol", "is_active": True},
    {"name": "Raki rrushi", "price": 2.0, "category": "Alcohol", "is_active": True},
    {"name": "Raki kumbulle", "price": 2.0, "category": "Alcohol", "is_active": True},
    {"name": "Vodka", "price": 2.5, "category": "Alcohol", "is_active": True},
    {"name": "Whisky", "price": 3.0, "category": "Alcohol", "is_active": True},
    {"name": "Gin", "price": 2.5, "category": "Alcohol", "is_active": True},
    {"name": "Mojito", "price": 4.5, "category": "Cocktails", "is_active": True},
    {"name": "Virgin Mojito", "price": 3.5, "category": "Cocktails", "is_active": True},
    {"name": "Aperol Spritz", "price": 5.0, "category": "Cocktails", "is_active": True},
    {"name": "Gin Tonic", "price": 4.0, "category": "Cocktails", "is_active": True},
    {"name": "Sex on the Beach", "price": 5.0, "category": "Cocktails", "is_active": True},
    {"name": "Blue Lagoon", "price": 4.5, "category": "Cocktails", "is_active": True},
    {"name": "Tequila Sunrise", "price": 4.5, "category": "Cocktails", "is_active": True},
    {"name": "Pina Colada", "price": 5.0, "category": "Cocktails", "is_active": True},
    {"name": "Long Island", "price": 6.0, "category": "Cocktails", "is_active": True},
    {"name": "Omëletë klasike", "price": 3.5, "category": "Breakfast", "is_active": True},
    {"name": "Omëletë me djathë", "price": 4.0, "category": "Breakfast", "is_active": True},
    {"name": "Omëletë me suxhuk", "price": 4.5, "category": "Breakfast", "is_active": True},
    {"name": "Vezë në sy", "price": 3.0, "category": "Breakfast", "is_active": True},
    {"name": "Mëngjes shtëpie", "price": 5.5, "category": "Breakfast", "is_active": True},
    {"name": "Mëngjes Tavora", "price": 6.5, "category": "Breakfast", "is_active": True},
    {"name": "Petulla me djathë", "price": 3.5, "category": "Breakfast", "is_active": True},
    {"name": "Petulla me mjaltë", "price": 3.0, "category": "Breakfast", "is_active": True},
    {"name": "Toast me proshutë", "price": 3.5, "category": "Breakfast", "is_active": True},
    {"name": "Supë pule", "price": 2.5, "category": "Soups", "is_active": True},
    {"name": "Supë viçi", "price": 3.0, "category": "Soups", "is_active": True},
    {"name": "Supë perimesh", "price": 2.5, "category": "Soups", "is_active": True},
    {"name": "Çorbë shtëpie", "price": 3.0, "category": "Soups", "is_active": True},
    {"name": "Çorbë me mish", "price": 3.5, "category": "Soups", "is_active": True},
    {"name": "Sallatë shopska", "price": 3.0, "category": "Salads", "is_active": True},
    {"name": "Sallatë greke", "price": 3.5, "category": "Salads", "is_active": True},
    {"name": "Sallatë pule", "price": 4.5, "category": "Salads", "is_active": True},
    {"name": "Sallatë tuna", "price": 4.5, "category": "Salads", "is_active": True},
    {"name": "Sallatë miks", "price": 3.0, "category": "Salads", "is_active": True},
    {"name": "Sallatë lakre", "price": 2.0, "category": "Salads", "is_active": True},
    {"name": "Sallatë domate", "price": 2.0, "category": "Salads", "is_active": True},
    {"name": "Meze e ftohtë e vogël", "price": 5.5, "category": "Appetizers", "is_active": True},
    {"name": "Meze e ftohtë e madhe", "price": 8.9, "category": "Appetizers", "is_active": True},
    {"name": "Djathë i bardhë", "price": 2.5, "category": "Appetizers", "is_active": True},
    {"name": "Djathë i pjekur", "price": 3.5, "category": "Appetizers", "is_active": True},
    {"name": "Kërpudha të pjekura", "price": 3.5, "category": "Appetizers", "is_active": True},
    {"name": "Bruschetta", "price": 3.0, "category": "Appetizers", "is_active": True},
    {"name": "Chicken fingers", "price": 4.0, "category": "Appetizers", "is_active": True},
    {"name": "Mozzarella sticks", "price": 4.0, "category": "Appetizers", "is_active": True},
    {"name": "Onion rings", "price": 3.0, "category": "Appetizers", "is_active": True},
    {"name": "Fileto pule", "price": 7.0, "category": "Main Dishes", "is_active": True},
    {"name": "Fileto viçi", "price": 10.0, "category": "Main Dishes", "is_active": True},
    {"name": "Chicken steak", "price": 7.5, "category": "Main Dishes", "is_active": True},
    {"name": "Chicken curry", "price": 7.5, "category": "Main Dishes", "is_active": True},
    {"name": "Mish viçi me sos", "price": 9.0, "category": "Main Dishes", "is_active": True},
    {"name": "Mish pule me kërpudha", "price": 7.5, "category": "Main Dishes", "is_active": True},
    {"name": "Gullash", "price": 6.5, "category": "Main Dishes", "is_active": True},
    {"name": "Oriz me mish pule", "price": 6.0, "category": "Main Dishes", "is_active": True},
    {"name": "Qebapa 5 copë", "price": 3.5, "category": "Grill", "is_active": True},
    {"name": "Qebapa 10 copë", "price": 6.0, "category": "Grill", "is_active": True},
    {"name": "Pleskavicë", "price": 5.0, "category": "Grill", "is_active": True},
    {"name": "Pleskavicë me djathë", "price": 6.0, "category": "Grill", "is_active": True},
    {"name": "Suxhuk shtëpie", "price": 5.5, "category": "Grill", "is_active": True},
    {"name": "Mish i përzier", "price": 9.0, "category": "Grill", "is_active": True},
    {"name": "Fileto pule në zgarë", "price": 7.0, "category": "Grill", "is_active": True},
    {"name": "Krahë pule", "price": 5.5, "category": "Grill", "is_active": True},
    {"name": "Pasta Carbonara", "price": 5.5, "category": "Pasta", "is_active": True},
    {"name": "Pasta Bolognese", "price": 5.5, "category": "Pasta", "is_active": True},
    {"name": "Pasta Arrabbiata", "price": 5.0, "category": "Pasta", "is_active": True},
    {"name": "Pasta Alfredo", "price": 5.5, "category": "Pasta", "is_active": True},
    {"name": "Pasta me pulë", "price": 6.0, "category": "Pasta", "is_active": True},
    {"name": "Pasta me tuna", "price": 6.0, "category": "Pasta", "is_active": True},
    {"name": "Margherita", "price": 4.5, "category": "Pizza", "is_active": True},
    {"name": "Funghi", "price": 5.0, "category": "Pizza", "is_active": True},
    {"name": "Prosciutto", "price": 5.5, "category": "Pizza", "is_active": True},
    {"name": "Capricciosa", "price": 6.0, "category": "Pizza", "is_active": True},
    {"name": "Diavola", "price": 6.0, "category": "Pizza", "is_active": True},
    {"name": "Tuna", "price": 6.0, "category": "Pizza", "is_active": True},
    {"name": "Vegetariane", "price": 5.5, "category": "Pizza", "is_active": True},
    {"name": "Tavora Special", "price": 7.0, "category": "Pizza", "is_active": True},
    {"name": "Toast klasik", "price": 2.5, "category": "Sandwiches", "is_active": True},
    {"name": "Toast pule", "price": 3.5, "category": "Sandwiches", "is_active": True},
    {"name": "Sanduiç pule", "price": 4.0, "category": "Sandwiches", "is_active": True},
    {"name": "Sanduiç tuna", "price": 4.0, "category": "Sandwiches", "is_active": True},
    {"name": "Club Sandwich", "price": 5.0, "category": "Sandwiches", "is_active": True},
    {"name": "Burger klasik", "price": 4.5, "category": "Sandwiches", "is_active": True},
    {"name": "Cheeseburger", "price": 5.0, "category": "Sandwiches", "is_active": True},
    {"name": "Chicken Burger", "price": 5.0, "category": "Sandwiches", "is_active": True},
    {"name": "Flija", "price": 4.5, "category": "Traditional Food", "is_active": True},
    {"name": "Pite me mish", "price": 3.0, "category": "Traditional Food", "is_active": True},
    {"name": "Pite me djathë", "price": 3.0, "category": "Traditional Food", "is_active": True},
    {"name": "Pite me spinaq", "price": 3.0, "category": "Traditional Food", "is_active": True},
    {"name": "Pasul", "price": 4.0, "category": "Traditional Food", "is_active": True},
    {"name": "Tavë kosi", "price": 6.0, "category": "Traditional Food", "is_active": True},
    {"name": "Speca të mbushur", "price": 5.5, "category": "Traditional Food", "is_active": True},
    {"name": "Sarma", "price": 5.5, "category": "Traditional Food", "is_active": True},
    {"name": "Mantia", "price": 5.0, "category": "Traditional Food", "is_active": True},
    {"name": "Kaçamak", "price": 4.0, "category": "Traditional Food", "is_active": True},
    {"name": "Pomfrit i vogël", "price": 1.5, "category": "Side Dishes", "is_active": True},
    {"name": "Pomfrit i madh", "price": 2.5, "category": "Side Dishes", "is_active": True},
    {"name": "Patate wedges", "price": 2.5, "category": "Side Dishes", "is_active": True},
    {"name": "Oriz", "price": 2.0, "category": "Side Dishes", "is_active": True},
    {"name": "Perime të pjekura", "price": 2.5, "category": "Side Dishes", "is_active": True},
    {"name": "Bukë", "price": 0.5, "category": "Side Dishes", "is_active": True},
    {"name": "Sos hudhre", "price": 0.5, "category": "Side Dishes", "is_active": True},
    {"name": "Sos pikant", "price": 0.5, "category": "Side Dishes", "is_active": True},
    {"name": "Ketchup", "price": 0.3, "category": "Side Dishes", "is_active": True},
    {"name": "Mayonnaise", "price": 0.3, "category": "Side Dishes", "is_active": True},
    {"name": "Tomëloriz", "price": 2.5, "category": "Desserts", "is_active": True},
    {"name": "Trileçe", "price": 3.0, "category": "Desserts", "is_active": True},
    {"name": "Bakllava", "price": 2.5, "category": "Desserts", "is_active": True},
    {"name": "Tiramisu", "price": 3.5, "category": "Desserts", "is_active": True},
    {"name": "Cheesecake", "price": 3.5, "category": "Desserts", "is_active": True},
    {"name": "Palaçinka me Nutella", "price": 3.5, "category": "Desserts", "is_active": True},
    {"name": "Palaçinka me fruta", "price": 4.0, "category": "Desserts", "is_active": True},
    {"name": "Akullore 1 top", "price": 1.0, "category": "Desserts", "is_active": True},
    {"name": "Akullore 3 topa", "price": 2.5, "category": "Desserts", "is_active": True},
    {"name": "Fruit salad", "price": 3.5, "category": "Desserts", "is_active": True},
    {"name": "Esspresso", "price": 0.5, "category": "Oferte", "is_active": True},
    {"name": "Machiato e madhe", "price": 0.5, "category": "Oferte", "is_active": True},
    {"name": "Machiato e vogel", "price": 0.5, "category": "Oferte", "is_active": True},
]
